version: '1.0'

steps:
  build-step:
    type: build
    image-name: b7beet
    dockerfile: Dockerfile
    context: .
  build-nginx:
    type: build
    image-name: beet-nginx
    dockerfile: nginx/Dockerfile
    context: nginx/
  spin-up:
    type: launch-composition
    composition:
      version: '2'
      services:
        mongo:
          image: mongo
        b7beet:
          image: ${{build-step}}
          ports:
            - 3000
          environment:
            MONGO_URI_DEV: 'mongodb://mongo/b7beet'
