version: '2'
volumes:
  mongodata:
  static-data:
services:
  web:
    build: .
    image: web
    ports:
      - 3000
  proxy:
    build: ./nginx
    ports:
      - 80:80
    volumes_from:
      - static-data
  mongo:
    image: mongo
    volumes_from:
      - mongodata
  static-data:
    image: ubuntu
    volumes:
      - /root:/root
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
